services:
  tor:
    image: tor-relay:latest
    container_name: tor
    ports:
      - 9001:9001
      - 9030:9030
    volumes:
      #- ./config:/etc/tor
      - ./data:/var/lib/tor
    restart: always
